### ISSUE TITLE
Ask for recorded video

### ISSUE THREAD

**Issue by gyillikci** [AlainPaillou/JETSONSKY#1]
Hello Alain,

Thanks for the work once again. 

Is there a chance you to upload some video recordings in 8 and 16 bit format for test purposes? 

Best,

Giray

**Comment by AlainPaillou** [comment]
Hello Giray,

for now, we can have 16 bits only with a camera. I can't manage 16bits video files with JetsonSky for post treatment.

I will try to see if OpenCV can read 16 bits video . If it can, i will make some test videos using 8 bits and 16 bits to allow post processing tests.

Alain

**Comment by gyillikci** [comment]
Thanks Alain, i am closing this issue then. I ll look for an update on the repo for new commits.
